%% \VignetteIndexEntry{Bioconductor LaTeX Style}

\documentclass{article}

<<style, echo=FALSE, results=tex>>=
BiocStyle::latex()
@
\newcommand{\exitem}[3]{\item \texttt{\textbackslash#1\{#2\}} #3 \csname#1\endcsname{#2}.}

\title{A probabilistic dynamical model for quantitative inference of the regulatory mechanism of transcription}
\author{Guido Sanguinetti, Magnus Rattray and Neil D. Lawrence}
%%\author{Muhammad A. Rahman}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

\begin{abstract}
Quantitative estimation of the regulatory relationship between transcription factors and genes is a fundamental stepping stone when trying to develop models of cellular processes. This task, however, is difficult for a number of reasons: transcription factors` expression levels are often low and noisy, and many transcription factors are post-transcriptionally regulated. It is therefore useful to infer the activity of the transcription factors from the expression levels of their target genes.
\end{abstract}

\tableofcontents

\section{Installing the \Biocpkg{chipDyno} package}
The recommanded way to install the \Bioconductor{} package \Biocpkg{chipDyno} is to use the \Rfunction{biocLite} function available in the \Bioconductor{} website. This way of installation should ensure that all the dependencies are met.

\begin{verbatim}
    > source ("www.//bioconductor.org/chipDyno.R")
    > biocLite("chipDyno")
\end{verbatim}

%%To determine the gene specific transcription factor activity of C. Elegans we have followd Sanguinetti's probabilistic dynamic model ~\cite{sanguinetti:01} for quantative inference.

\section{Loading the package and getting help}
The first step in any \Biocpkg{chipDyno} analysis is to load the package. This package can be loaded when the \R{} console is ready. At the \R{} console type the following command:

\begin{verbatim}
    > library("chipDyno")
\end{verbatim}

Command \Rfunction{help} can be used to get help on any function. For example, to get help on the \Rfunction{chipDynoLikeStatGrad} type the following (both of them have the similar output):

\begin{verbatim}
    > help(chipDynoLikeStatGrad)
    > ?chipDynoLikeStatGrad
\end{verbatim}

\section{Input data and preparations}
If the data is in Affymetrix CEL files then it may requered to do some preprocessing. This CEL files can be extracted using the bioconductor package \Biocpkg{puma} ~\cite{puma}. \Biocpkg{puma} usually stores the point expressione in \file{*\_exprs.csv} file and defferent levels of unicertainities in \file{*\_se.csv} files as Comma-separated values.

Load the point expression levels data. Here the data was stored in comma-seperated value (csv) file.

<<echo=TRUE>>=
data_file = 
  "/home/muhammad/Dropbox/CElegans/cluster/3exp_15dp_After_meeting/eset_cElegans_exprs.csv"
data_file
data_dictionary <- read.table(data_file, header = TRUE, sep = ",", quote = "", 
                    dec = ".", , na.strings = "NA", colClasses = NA, nrows = -1, skip = 0, 
                    check.names = TRUE, fill = TRUE, strip.white = FALSE,  
                    blank.lines.skip = TRUE, comment.char = "#", 
                    allowEscapes = FALSE, flush = FALSE)
data_dictionary[is.na(data_dictionary)] <- 0
probeId = data_dictionary[,1]
as.matrix(probeId[1:7],,1)
@

In our experimental data set there was 3 replication of the same experiment with 5 experimental time points with different environmental conditions. So there was (3x5=) 15 time points. We will to reorganize this datapoint maintaining the time series for different experiment. For our this example we will consider the data obtained from the second experiment.

<<echo=TRUE>>=
data = data_dictionary[,2:ncol(data_dictionary)]
data_sample1 <- cbind(data[,10],data[,1],data[,4],data[,7],data[,13])
data_sample2 <- cbind(data[,11],data[,2],data[,5],data[,8],data[,14])
data_sample3 <- cbind(data[,12],data[,3],data[,6],data[,9],data[,15])
data = data_sample2
data_sample1[1:7, 1:5]
@

Load the the standard errors-

<<echo=TRUE>>=
vars_file = 
  "/home/muhammad/Dropbox/CElegans/cluster/3exp_15dp_After_meeting/eset_cElegans_se.csv"

vars_dictionary <- read.table(vars_file, header = TRUE, sep = ",", quote = "", 
                  dec = ".", , na.strings = "NA", colClasses = NA, nrows = -1, skip = 0, 
                  check.names = TRUE, fill = TRUE, strip.white = FALSE, 
                  blank.lines.skip = TRUE, comment.char = "#", 
                  allowEscapes = FALSE, flush = FALSE)
vars_dictionary[is.na(vars_dictionary)] <- 0
vars = vars_dictionary[,2:ncol(vars_dictionary)]
vars_sample1 <- cbind(vars[,10],vars[,1],vars[,4],vars[,7],vars[,13])
vars_sample2 <- cbind(vars[,11],vars[,2],vars[,5],vars[,8],vars[,14])
vars_sample3 <- cbind(vars[,12],vars[,3],vars[,6],vars[,9],vars[,15])
vars = vars_sample2 # Choose the sample
@


\section{??????????}

Add the following to your package \file{DESCRIPTION} file:
\begin{verbatim}
    Suggests: BiocStyle
\end{verbatim}
and this code chunk to the preamble of each vignette:
\begin{verbatim}
    <<style, eval=TRUE, echo=FALSE, results=tex>>=
    BiocStyle::latex()
    @ 
\end{verbatim}
Arguments to \Rfunction{latex} are passed to \Rcode{options}. The default sets \Rcode{width=90}, which is optimal for the default font size 11pt; for smaller/larger font size please consider increasing/decreasing this value.

The style features headers containing the title of the vignette as defined by \verb+\title+. If you wish to override it, e.g.~in the case of long titles, add the following line to the preamble of your vignette:
\begin{verbatim}
    \renewcommand{\thetitle}{Short header title}
\end{verbatim}

\Biocpkg{BiocStyle} automatically attaches the following \LaTeX{} packages: \texttt{color}, \texttt{fancyhdr}, \texttt{geometry}, \texttt{helvet}, \texttt{hyperref}, \texttt{sectsty}, \texttt{Sweave} and \texttt{titling}, so there is no need to reload them with \verb+\usepackage+.

\section{Markup commands}
\Biocpkg{BiocStyle} introduces the following additional markup styling commands useful in typical \Bioconductor{} vignettes.\\\\
%%
Software:
\begin{itemize}
  \item \verb+\R{}+ and \verb+\Bioconductor{}+ to reference \R{} software and the \Bioconductor{} project.
  \exitem{software}{GATK}{to reference third-party software, e.g.,}
\end{itemize}
\vspace{1em}
%%
Packages:
\begin{itemize}
  \exitem{Biocpkg}{IRanges}{for \Bioconductor{} software packages, including a link to the release version landing page,}
  \exitem{Biocannopkg}{org.Hs.eg.db}{for \Bioconductor{} annotation packages, including a link to the release version landing page,}
  \exitem{Biocexptpkg}{parathyroidSE}{for \Bioconductor{} experiment data packages, including a link to the release version landing page,}
  \exitem{CRANpkg}{data.table}{for \R{} packages available on CRAN, including a link to the FHCRC CRAN mirror landing page,}
  \exitem{Rpackage}{MyPkg}{for \R{} packages that are \emph{not} available on \Bioconductor{} or CRAN,}
\end{itemize}
\vspace{1em}
%%
Code:
\begin{itemize}
  \exitem{Rfunction}{findOverlaps}{for functions}
  \exitem{Robject}{olaps}{for variables}
  \exitem{Rclass}{GRanges}{when refering to a formal class}
  \exitem{Rcode}{log(x)}{for \R{} code,}
\end{itemize}
\vspace{1em}
%%
Communication:
\begin{itemize}
  \exitem{comment}{comment to the user}{communicates a}
  \exitem{warning}{common pitfalls}{signals}
  \exitem{fixme}{incomplete functionality}{provides an indication of}
\end{itemize}
\vspace{1em}
%%
General:
\begin{itemize}
  \exitem{email}{user@domain.com}{to provide a linked email address,}
  \exitem{file}{script.R}{for file names and file paths}
\end{itemize}

%---------------------------------------------------------
\section{Sectioning: this is a section}
%---------------------------------------------------------

Use \verb+\tableofcontents+ for a hyperlinked table of contents,
\verb+\section+, \verb+\subsection+, \verb+\subsubsection+ for structuring your vignette.

\subsection{This is a subsection}
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

\subsubsection{This is a subsubsection}
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
 
%---------------------------------------------------------
\section{Including a figure}
%---------------------------------------------------------

Besides the usual \LaTeX{} capabilities (\verb+figure+ environment and
\verb+includegraphics+ command), \file{Bioconductor.sty} defines a
shortcut \verb+\incfig{filename}{width}{shorttitle}{extendedcaption}+,
which expects four arguments:
\begin{description}
\item[filename] The name of the figure file, also used as the label by
  which the float can be refered to by \verb+\ref{}+. Some
  \software{Sweave} and \CRANpkg{knitr} options place figures in a
  sub-folder; the sub-folder should be included in the file name.
\item[width] Figure width.
\item[shorttitle] A short description, used in the list of figures and
  printed in bold as the first part of the caption.
\item[extendedcaption] Continuation of the figure caption.
\end{description}
Thus
\begin{verbatim}
    <<figureexample,fig=TRUE,include=FALSE,width=4.2,height=4.6>>=
    v = seq(0, 60i, length=1000)
    plot(abs(v)*exp(v), type="l", col="Royalblue")
    @ 
    \incfig{LatexStyle-figureexample}{0.25\textwidth}{A curve.}
        {The code that creates this figure is shown in the code chunk.}
    as shown in Figure~\ref{LatexStyle-figureexample}.
\end{verbatim}
results in 
<<figureexample,fig=TRUE,include=FALSE,width=4.2,height=4.6>>=
v = seq(0, 60i, length=1000)
plot(abs(v)*exp(v), type="l", col="Royalblue")
@ 
%% 
\incfig{figure/LatexStyle-figureexample.pdf}{0.25\textwidth}{A curve.}{The code
  that creates this figure is shown in the code chunk.}  as shown in
Figure~\ref{LatexStyle-figureexample}. (Use
\verb+\ref{figure/figureexample}+ with \CRANpkg{knitr}).

%---------------------------------------------------------
\section{Session info}
%---------------------------------------------------------
Here is the output of \Rfunction{sessionInfo} on the system on which
this document was compiled:
<<sessionInfo, results=tex, print=TRUE>>=
toLatex(sessionInfo())
@


%\bibliographystyle{abbrv}
%\bibliographystyle{alpha}
\bibliographystyle{apalike}

\bibliography{bib_chipDyno}

\end{document}